# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 3
  reviewers:
    - "@bringg/data"
  assignees:
    - EdenHayikBringg
  registries:
  - npm-registry-registry-npmjs-org
  groups:
    bringg:
      patterns:
      - "@bringg/*"
