#
# Default values for all environments!
# Should be used with per env value files
#
createService: true

owner: data

service:
  endpoints:
  - path: /data-agents-service
    stripPath: true

resources:
  requests:
    cpu: 100m
    memory: 172Mi
  limits:
    cpu: 500m
    memory: 512Mi

envVariables:
- name: OPENAI_API_KEY
  valueFrom:
    secretKeyRef:
      key: openai_api_key
      name: ai-secrets

- name: LANGSMITH_API_KEY
  valueFrom:
    secretKeyRef:
      key: langsmith_api_key
      name: ai-secrets

- name: LANGSMITH_TRACING
  value: true

- name: LANGSMITH_ENDPOINT
  value: "https://api.smith.langchain.com"

- name: LANGSMITH_PROJECT
  value: "data-agents-service"
